# Generated by Django 5.2.7 on 2025-12-21 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_solicitacaoprofessor'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacaoprofessor',
            name='curriculo',
            field=models.FileField(blank=True, help_text='Envie seu currículo (PDF, DOC, DOCX)', null=True, upload_to='curriculos/'),
        ),
        migrations.AddField(
            model_name='solicitacaoprofessor',
            name='links',
            field=models.TextField(blank=True, help_text='Links para portfólio, LinkedIn, GitHub, etc. (opcional)', null=True),
        ),
    ]
