# Generated by Django 5.2.7 on 2025-12-21 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_solicitacaoprofessor_curriculo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacaoprofessor',
            name='curriculo',
            field=models.FileField(help_text='Envie seu currículo (PDF, DOC, DOCX)', upload_to='curriculos/'),
        ),
    ]
