# Generated by Django 5.2.7 on 2025-12-21 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_alter_solicitacaoprofessor_curriculo'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacaoprofessor',
            name='notificacao_vista',
            field=models.BooleanField(default=False, help_text='Se o usuário já viu a notificação de resposta'),
        ),
    ]
