# Generated by Django 5.2.7 on 2025-12-21 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_notificacao'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notificacao',
        ),
    ]
