# Generated by Django 5.2.7 on 2025-12-08 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infohelp', '0004_populate_categories_difficulties'),
    ]

    operations = [
        migrations.AddField(
            model_name='aula',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='aulas/'),
        ),
    ]
